# Generated by Django 2.0.1 on 2019-06-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='data',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='additional',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='dessert',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='main',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
